### ISSUE TITLE
The stop hook appears to be broken

### ISSUE THREAD

**Issue by mbruzek** [chuckbutler/flannel-docker-charm#4]
While testing the flannel-docker charm I was trying to reset the environment (juju deployer -T) several times.  The stop hook resulted in an error. This error cause me to have to use --force to destroy the machine.

We should make sure that even the stop hook completes successfully.

**Comment by lazypower** [comment]
This is actually affecting the Docker charm, not docker-flannel. Moving this over to docker here: https://github.com/chuckbutler/docker-charm/issues/18
